markets:
  - arbuz
  - vprestige
  - magnum
  - technodom
  - sulpak
  - europharma
  - flip
  - leroy_merlin
  - ayanmarket

cities:
  - almaty
  - aktau

headless: true
debug: false
max_retries: 2
data_dir: data
